# =====================================================================
# LangChain Chat History - Part 1: Message Types
# =====================================================================
#
# In LangChain, conversation transcripts are represented as lists of
# message objects. Each object belongs to a class representing its role:
#
# 1. SystemMessage: Used to instruct the AI on its behavior, persona,
#    rules, constraints, or tone. Usually passed at the very start.
# 2. HumanMessage: Represents the user's input/query.
# 3. AIMessage: Represents the response generated by the LLM.
#
# Here we are simulating a customer support chatbot for an online shoe retailer
# called "Soleful Steps". We will pass a system message defining the store's
# guidelines, followed by a sequence of user questions and AI replies.
# =====================================================================

import os
from dotenv import load_dotenv
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langchain_google_genai import ChatGoogleGenerativeAI


def main():
    # 1. Load environment variables (contains GOOGLE_API_KEY)
    load_dotenv()
    
    if not os.environ.get("GOOGLE_API_KEY"):
        print("[ERROR] GOOGLE_API_KEY not found in environment. Please add it to your .env file.")
        return
        
    # 2. Initialize Gemini (gemini-3.5-flash)
    # We use temperature=0 for consistent, predictable answers during learning.
    llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)
    print("Gemini model initialized successfully.\n")
    
    # 3. Define the message history list
    # Notice how we start with a SystemMessage to set the bot's behavior guidelines.
    # The order of the subsequent HumanMessage and AIMessage objects mimics a real conversation.
    messages = [
        SystemMessage(
            content=(
                "You are a helpful customer support agent for 'Soleful Steps', a premium shoe store. "
                "Always be polite, professional, and refer to shoes as 'sole-mates'. "
                "Keep your answers concise (under 2 sentences) and offer a 10% discount code "
                "('SOLE10') if the customer asks about shipping costs."
            )
        ),

        # Round 1 of chat
        HumanMessage(content="Hi, do you sell running shoes?"),
        AIMessage(content="Hello! Yes, we do offer a wide selection of premium running sole-mates to keep you moving comfortably. How can I help you find the perfect pair today?"),

        # Round 2 of chat - User asks a follow-up
        HumanMessage(content="How much is shipping? And does it take long to arrive?")
    ]
    
    print("--- Conversation History Sent to LLM ---")
    for msg in messages:
        role = msg.__class__.__name__
        print(f"[{role}]: {msg.content}")
    print("-" * 40)
    
    # 4. Invoke the model
    # We pass the entire list of messages. The LLM processes all of them
    # to understand that the user is talking about running shoes, asking about
    # shipping, and that it must refer to shoes as 'sole-mates' and offer 'SOLE10'.
    print("Invoking LLM...")
    response = llm.invoke(messages)
    
    print(f"\n[AI Response]:\n{response.content}")
    print("\n" + "=" * 60)


if __name__ == "__main__":
    main()



# Because LLMs are stateless, passing the historical messages list is what
# allows it to know the customer's name, preferences, or context in subsequent turns.
# In real world also this is exactly how every production AI chatbot works under the hood, 
# but instead of keeping messages in temporary Python lists or RAM (InMemoryChatMessageHistory), 
# production systems use database-backed history stores.
# Every chat user is assigned a unique id (e.g. session_id) , and when  user sends a message, 
# the chatbot backend queries a database (like PostgreSQL, Redis, or DynamoDB) to fetch all 
# historical messages associated with that session_id.
# LangChain makes this seamless by offering classes like SQLChatMessageHistory or RedisChatMessageHistory.
